// Data access for users. Parameterized queries only; it returns rows and
// knows nothing about HTTP or hashing. The password_hash column never
// travels beyond the service layer — the mapper drops it.
import { pool } from '../../database/pool.js';

const USER_COLUMNS = `
  id,
  email,
  password_hash,
  role,
  created_at
`;

export async function findByEmail(email, db = pool) {
  const result = await db.query(
    `SELECT ${USER_COLUMNS} FROM users WHERE email = $1`,
    [email]
  );
  return result.rows[0] ?? null;
}

export async function findById(id, db = pool) {
  const result = await db.query(
    `SELECT ${USER_COLUMNS} FROM users WHERE id = $1`,
    [id]
  );
  return result.rows[0] ?? null;
}

export async function insertUser({ email, passwordHash }, db = pool) {
  // id, role and created_at are generated by the database. Role is NOT a
  // parameter on purpose: registration cannot choose it.
  const result = await db.query(
    `INSERT INTO users (email, password_hash)
     VALUES ($1, $2)
     RETURNING ${USER_COLUMNS}`,
    [email, passwordHash]
  );
  return result.rows[0];
}
