export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
};

// Reglas: De qué estado a qué estado se permite pasar
export const VALID_TRANSITIONS = {
  PENDING: [REQUEST_STATUS.IN_PROGRESS, REQUEST_STATUS.CANCELLED],
  IN_PROGRESS: [REQUEST_STATUS.RESOLVED, REQUEST_STATUS.CANCELLED],
  RESOLVED: [REQUEST_STATUS.CLOSED, REQUEST_STATUS.CANCELLED],
  CLOSED: [],
  CANCELLED: []
};